# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DESZaM15vdPonxza54WMko0FGxQwidHn
"""

from google.colab import drive
from tensorflow.keras.models import load_model

# Mount Google Drive
drive.mount('/content/drive')

# Define model path
model_path = '/content/drive/MyDrive/IronHack/vgg16_animal_classifier.keras'

# Load the model
model = load_model(model_path)
print("✅ Model loaded from Google Drive!")

import gradio as gr
import numpy as np
from tensorflow.keras.preprocessing import image

# Your class labels
class_labels = ['butterfly', 'cat', 'chicken', 'cow', 'dog', 'elephant', 'horse', 'sheep', 'spider', 'squirrel']

def predict_animal(img):
    img = img.resize((128, 128))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0

    prediction = model.predict(img_array)
    predicted_index = np.argmax(prediction)
    return class_labels[predicted_index]

# Gradio Interface
interface = gr.Interface(
    fn=predict_animal,
    inputs=gr.Image(type="pil"),
    outputs="label",
    title="Animal Classifier (VGG16)",
    description="Upload an image of an animal and get a prediction!"
)

interface.launch()